### ISSUE TITLE
Status of PuppetServer / PuppetDB packages for Debian 12

### ISSUE THREAD

**Issue by smortex** [voxpupuli/community-triage#10]
Related discussion:
https://github.com/puppetlabs/community/discussions/65

**Comment by binford2k** [comment]
This is blocking Foreman support.

**Comment by tuxmea** [comment]
In May 15th voxpupuli meeting it was mentioned that Debian is not supported by PE due to no commercial support for Debian available.

Note: There is commercial support for Debian available. See https://www.debian.org/consultants/

**Comment by davidsandilands** [comment]
Josh informed me that 

 the unicorn team have received some training to help working on a couple of things of interest, so ezbake and Debian 12 Server should receive some work shortly but this isn't a commitment to do dates yet
