### ISSUE TITLE
Talk about the Election

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/community-triage#8]
We currently have 5 nominations.

* Does everybody accept the nomination?
* Do we need an election?
* Should the PMC period last two years instead of one?

**Comment by binford2k** [comment]
We have 7 nominations. Starting the election today.

**Comment by binford2k** [comment]
election voting period kicked off now. https://voxpupuli.org/blog/2024/04/09/pmc-elections-voting-period/
